Config.Themes = {
    {
        id = 'dark',
        label = 'W2F Dark',
        bg = '#06080f',
        surface = '#0e1322',
        accent = '#2d7fff',
        accentSoft = '#5dd2ff',
        text = '#f4f7ff',
        muted = '#8693a8',
        danger = '#ef4444',
        success = '#22c55e',
        gold = '#f5c44e',
    },
    {
        id = 'graphite',
        label = 'Graphite',
        bg = '#0d0f12',
        surface = '#1a1d24',
        accent = '#5dd2ff',
        accentSoft = '#a9eaff',
        text = '#eef1f6',
        muted = '#7d8493',
        danger = '#ef4444',
        success = '#22c55e',
        gold = '#f5c44e',
    },
    {
        id = 'midnight',
        label = 'Midnight Navy',
        bg = '#04081c',
        surface = '#0b1238',
        accent = '#2d7fff',
        accentSoft = '#8ab8ff',
        text = '#f1f4ff',
        muted = '#8390b7',
        danger = '#ef4444',
        success = '#22c55e',
        gold = '#f5c44e',
    },
}

Config.Wallpapers = {
    { id = 'w2f_default', label = 'W2F Signature', kind = 'gradient',
      from = '#020514', to = '#0b1f4a' },
    { id = 'w2f_aurora', label = 'Aurora', kind = 'gradient',
      from = '#0b1f4a', to = '#5dd2ff' },
    { id = 'w2f_carbon', label = 'Carbon', kind = 'gradient',
      from = '#06080f', to = '#1a1d24' },
    { id = 'w2f_gold', label = 'Gold Hour', kind = 'gradient',
      from = '#0e1322', to = '#f5c44e' },
}
